/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubgeoIndustrialRouteImport } from './routes/subgeo-industrial'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as ContactRouteImport } from './routes/contact'
<<<<<<< HEAD
import { Route as BranchesRouteImport } from './routes/branches'
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
import { Route as BeautyRouteImport } from './routes/beauty'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubgeoIndustrialRoute = SubgeoIndustrialRouteImport.update({
  id: '/subgeo-industrial',
  path: '/subgeo-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
const BeautyRoute = BeautyRouteImport.update({
  id: '/beauty',
  path: '/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beauty': typeof BeautyRoute
<<<<<<< HEAD
  '/branches': typeof BranchesRoute
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
  '/contact': typeof ContactRoute
  '/pharmacy': typeof PharmacyRoute
  '/subgeo-industrial': typeof SubgeoIndustrialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beauty': typeof BeautyRoute
<<<<<<< HEAD
  '/branches': typeof BranchesRoute
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
  '/contact': typeof ContactRoute
  '/pharmacy': typeof PharmacyRoute
  '/subgeo-industrial': typeof SubgeoIndustrialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beauty': typeof BeautyRoute
<<<<<<< HEAD
  '/branches': typeof BranchesRoute
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
  '/contact': typeof ContactRoute
  '/pharmacy': typeof PharmacyRoute
  '/subgeo-industrial': typeof SubgeoIndustrialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beauty'
<<<<<<< HEAD
    | '/branches'
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
    | '/contact'
    | '/pharmacy'
    | '/subgeo-industrial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beauty'
<<<<<<< HEAD
    | '/branches'
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
    | '/contact'
    | '/pharmacy'
    | '/subgeo-industrial'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beauty'
<<<<<<< HEAD
    | '/branches'
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
    | '/contact'
    | '/pharmacy'
    | '/subgeo-industrial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeautyRoute: typeof BeautyRoute
<<<<<<< HEAD
  BranchesRoute: typeof BranchesRoute
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
  ContactRoute: typeof ContactRoute
  PharmacyRoute: typeof PharmacyRoute
  SubgeoIndustrialRoute: typeof SubgeoIndustrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subgeo-industrial': {
      id: '/subgeo-industrial'
      path: '/subgeo-industrial'
      fullPath: '/subgeo-industrial'
      preLoaderRoute: typeof SubgeoIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
    '/beauty': {
      id: '/beauty'
      path: '/beauty'
      fullPath: '/beauty'
      preLoaderRoute: typeof BeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeautyRoute: BeautyRoute,
<<<<<<< HEAD
  BranchesRoute: BranchesRoute,
=======
>>>>>>> a5a45ed9d2c87926bfbef2ac01c730ed6ad25396
  ContactRoute: ContactRoute,
  PharmacyRoute: PharmacyRoute,
  SubgeoIndustrialRoute: SubgeoIndustrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
